# Generated by Django 4.0.4 on 2022-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(related_name='item_labels', to='home.label'),
        ),
    ]
