# Generated by Django 4.0.4 on 2022-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueuser',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogueuser',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
